//===- XlnxOps.cpp - Xlnx dialect ops --------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/Xlnx/XlnxOps.h"
#include "circt/Dialect/Xlnx/XlnxDialect.h"
#include "mlir/IR/OpAsmSupport.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Support/LLVM.h"

using namespace mlir;
using namespace circt;
using namespace circt::xlnx;

//===----------------------------------------------------------------------===//
// XlnxNLutOp
//===----------------------------------------------------------------------===//

LogicalResult XlnxNLutOp::verify() {
  // Verify that the number of inputs is within the valid range (1-6)
  size_t numInputs = getInputs().size();
  if (numInputs < 1 || numInputs > 6) {
    return emitOpError() << "requires between 1 and 6 inputs, but got " 
                         << numInputs << " inputs";
  }
  
  // The INIT attribute is a 64-bit value, which is sufficient for up to 6 inputs
  // (2^6 = 64 entries). For fewer inputs, only the lower bits are used.
  return success();
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/Xlnx/Xlnx.cpp.inc" 